repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      args: [--max-line-length=88]
  - repo: local
    hooks:
      - id: xenon
        name: xenon
        entry: run.sh xenon
        language: script
        types: [python]
  - repo: local
    hooks:
      - id: test
        name: tests
        entry: run.sh tests
        language: script
        types: [python]
