version: '3.7'
services:
  repo_data:
    image: repo_data_web
    build:
      context: .
      target: web
    ports:
      - "8000:8000"
    environment:
      - APP_ENVIRONMENT=dev
    env_file:
      - .env
    command: sh /code/run.sh api_web
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  dbdata:
